#!/usr/bin/env node


/*
generate_ast.mjs - main orchestrator file.

commands to use for runnig:

docker run -it --rm -v ${PWD}:/app -w /app node:25-slim node generate_ast.mjs

Note: You need to have Node.js downloaded. I have it downloaded on windows through Docker. If you download it differently 
you might have to use a different run command. This is how I downloaded the nodes:

docker pull node:24-slim
docker run -it --rm --entrypoint sh node:24-slim
npm install @unified-latex/unified-latex-util-parse

*/


//#!/usr/bin/env node

/*Import Unified Parser*/
import * as fs from "fs";
import { getParser } from "@unified-latex/unified-latex-util-parse";
import { parseExpression } from "./parserHelpers.mjs";


function printEdgeAst(einsumList) {
    if (einsumList.length === 0) {
        console.log("(empty AST)");
        return;
    }

    for (const einsum of einsumList) {
        if (einsum.name.length > 1) {
            console.warn(`"${einsum.name}" is a multi-character tensor name.`);
        }

        console.log(`\nEinsum ${einsum.name}:`);
        console.log(`  - Tensors:`);

        for (const tensor of einsum.tensors) {
            const autoGenerated = Object.values(tensor.rankVariableExpressions).every(v => v === "Null");

            console.log(`    - Tensor:`);
            console.log(`        - Type: ${tensor.role}`);
            console.log(`        - Name: "${tensor.name}"`);

            // Warn if rank list was auto-generated (no superscript was given)
            if (autoGenerated) {
                console.log(`        - Rank List: [${tensor.rankList.map(r => `"${r}"`).join(", ")}]  ← auto-generated, warn`);
            } else {
                console.log(`        - Rank List               : [${tensor.rankList.map(r => `"${r}"`).join(", ")}]`);
            }

            console.log(`        - Rank Variable Expressions:`);
            for (const [rankVar, expr] of Object.entries(tensor.rankVariableExpressions)) {
                console.log(`            - "${rankVar}": ${expr}`);
            }
        }

        if (einsum.operator.length > 0) {
            console.log(`  - Operator : [${einsum.operator.join(", ")}]`);
        }
        if (einsum.map.length > 0) {
            console.log(`  - Map      : [${einsum.map.join(", ")}]`);
        }
        if (einsum.reduce.length > 0) {
            console.log(`  - Reduce   : [${einsum.reduce.join(", ")}]`);
        }
        if (einsum.populate.length > 0) {
            console.log(`  - Populate : [${einsum.populate.join(", ")}]`);
        }

        console.log("─".repeat(50));
    }
}



const INPUT_FILE = "example3_tester_code.txt";
const rawContent = fs.readFileSync(INPUT_FILE, "utf8");
console.log("Given LaTeX Expression:\n", rawContent, "\n");

const parser = getParser();
const parsedAst = parser.parse(rawContent);

if (parsedAst.content && parsedAst.content.length > 0) {
    for (const node of parsedAst.content) {

        console.log("\n=== DEBUGGING OUTPUT ===");

        const edgeAst = parseExpression(node.content);

        // console.log("=== Raw Unified Parser output ===");
        // console.log(JSON.stringify(node.content, null, 2));

        // console.log("\n=== EDGE AST ===");
        // printEdgeAst(edgeAst);

        
    }
}